name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  # ここを1つだけにします（バージョンを最新の 1.0.5 に上げるのがおすすめです）
  mesh: ^0.5.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/menu.png
    - assets/icons/bat.png
    - assets/icons/bch.png
    - assets/icons/btc.png
    - assets/icons/xrp.png
    - assets/icons/header.png
    - assets/icons/Home.svg
    - assets/icons/listsearch.svg
    - assets/icons/order.svg
    - assets/icons/assets.svg
    - assets/icons/Othermenu.svg